version: '3.8'

services:
  
  postgresdb:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: my_database
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    depends_on:
      - postgresdb

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
    restart: always